import os
AWS_ACCESS_KEY_ID_ENV_KEY = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY_ENV_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")

print("AWS_ACCESS_KEY_ID:", AWS_ACCESS_KEY_ID_ENV_KEY)
print("AWS_SECRET_ACCESS_KEY:", AWS_SECRET_ACCESS_KEY_ENV_KEY)
